spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/stock
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug

external:
  api:
    id: PcqeBZmnsgUIVu02TLDJ
    password: oacFmqOCBg