spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: stockuser
    password: stock0818
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace
server:
  port: ${PORT:8080}
external:
  api:
    id: PcqeBZmnsgUIVu02TLDJ
    password: oacFmqOCBg